src/views/admin.py
'''Index view module'''

from functools import wraps
from ..model import SubmitForm
from ..model.Common import Common
from ..model.Reservation import Reservation
from flask import Blueprint, session, request, render_template, redirect, url_for

ADMIN = Blueprint('admin', __name__)

def login_required(func):
    '''A decorated function that check if the user has logged in.'''
    @wraps(func)
    def decorated_function(*args, **kwargs):
        '''decorated_function'''
        if not is_login():
            return redirect(url_for('admin.login', next=request.url))
        return func(*args, **kwargs)
    return decorated_function

def is_login():
    '''Check if the user has login'''
    if 'isLogin' in session.keys():
        if session['isLogin']:
            return True
    return False

# -------------------------------------------------------------------------------------
# Route
# -------------------------------------------------------------------------------------
@ADMIN.route('/api/pass_reservation', methods=["GET", "POST"])
@login_required
def pass_reservation():
    '''Pass the reservation'''
    if request.method == 'POST':
        try:
            Reservation.change_status(request.form['id'], 1)
        except BaseException:
            return '0'
    return '1'

@ADMIN.route('/api/pend_reservation', methods=["GET", "POST"])
@login_required
def pend_reservation():
    '''Let the reservation be pended'''
    if request.method == 'POST':
        try:
            Reservation.change_status(request.form['id'], 0)
        except BaseException:
            return '0'
    return '1'

@ADMIN.route('/api/refuse_reservation', methods=["GET", "POST"])
@login_required
def refuse_reservation():
    '''Refuse the reservation'''
    if request.method == 'POST':
        try:
            Reservation.change_status(request.form['id'], -1)
        except BaseException:
            return '0'
    return '1'

@ADMIN.route('/manage_future', methods=["GET", "POST"])
@login_required
def manage_future():
    '''Manage future reservation.'''
    data = Reservation.admin_get_future_reservation()
    result = {}
    result_reverse = {}
    for item in data:
        try:
            result[item['reservdate']].append(item)
        except BaseException:
            result[item['reservdate']] = [item]
    for key in list(result.keys())[::-1]:
        result_reverse[key] = result[key]
    return render_template('admin/manage_future.html', all_data=result_reverse, is_login=True)

@ADMIN.route('/api/manage_future', methods=["GET", "POST"])
@login_required
def api_manage_future():
    '''Manage future reservation.'''
    data = Reservation.admin_get_future_reservation()
    result = {}
    result_reverse = {}
    for item in data:
        try:
            result[item['reservdate']].append(item)
        except BaseException:
            result[item['reservdate']] = [item]
    for key in list(result.keys())[::-1]:
        result_reverse[key] = result[key]
    return Common.json_beautify(result_reverse)

@ADMIN.route('/get_all', methods=["GET", "POST"])
@login_required
def get_all():
    '''Show all reservation'''
    return render_template('admin/get_all.html', is_login=True, all_data=Reservation.get_all_reservation())

@ADMIN.route('/')
@login_required
def index():
    '''Admin page'''
    return render_template('admin/admin.html', is_login=True)

@ADMIN.route('/login', methods=['GET', 'POST'])
def login():
    '''Login func'''
    if is_login():
        return redirect(url_for('admin.index'))

    if request.method == 'POST':
        if Common.is_valid(request.form['username'], request.form['password']):
            session['username'] = request.form['username']
            session['isLogin'] = True
            return redirect(url_for('admin.index'))
        else:
            return render_template('admin/login.html', tip='用户名或者密码错误！')
    return render_template('admin/login.html')

@ADMIN.route('/logout')
def logout():
    '''Log out func'''
    session.pop('username', None)
    session['isLogin'] = False
    session['userIsLogin'] = False
    return redirect(url_for('index.index'))

src/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <title>弘毅学堂活动室预约系统</title>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet"
          href="{{ url_for('static', filename='materializecss/css/materialize.min.css') }}"
          media="screen,projection"/>

    <!--Import my custom css-->
    <link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='custom/css/main.css') }}"/>

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <!-- Insert favicon.ico -->
    <link
            rel="shortcut icon"
            href="{{ url_for('static', filename='favicon.ico') }}"
            type="image/x-icon"
    />
</head>

<body>
<nav>
    <div class="nav-wrapper pink">
        <a href="{{ url_for('index.index') }}" class="brand-logo">&nbsp&nbsp 活动室预约</a>
        <a href="#" data-activates="mobile-menu" class="button-collapse"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down">
            <li><a href="{{ url_for('index.index') }}">Home</a></li>
            <li><a href="{{ url_for('user.index') }}">User</a></li>
            <li><a href="#notifications" class="modal-trigger">Tips</a></li>
            <li><a href="http://touko.moe">About</a></li>
            <li><a href="{{ url_for('admin.index') }}">Admin</a></li>
            {% if is_login %}
                <li><a href="{{ url_for('admin.logout') }}">Logout</a></li>
            {% endif %}
        </ul>
        <ul class="side-nav" id="mobile-menu">
            <li><a href="{{ url_for('index.index') }}">Home</a></li>
            <li><a href="{{ url_for('user.index') }}">User</a></li>
            <li><a href="#notifications" class="modal-trigger">Tips</a></li>
            <li><a href="http://touko.moe">About</a></li>
            <li><a href="{{ url_for('admin.index') }}">Admin</a></li>
            {% if is_login %}
                <li><a href="{{ url_for('admin.logout') }}">Logout</a></li>
            {% endif %}
        </ul>
    </div>
</nav>

{% block contents %} {% endblock contents %}



<section id="footer" class="scrollspy">
    <footer class="page-footer pink">
        <div class="container">
            <div class="row">
                <div class="col l6 s12">
                    <h5 class="white-text">弘毅学堂活动室预约系统</h5>
                    <p class="grey-text text-lighten-4">使用请遵守各项规则。<br/>合理安排时间，保持活动室整洁。</p>
                </div>
                <div class="col l4 offset-l2 s12">
                    <h5 class="white-text">Links</h5>
                    <ul>
                        <li><a href="#notifications" class="grey-text text-lighten-3 modal-trigger">注意事项</a></li>
                        <li><a href="http://touko.moe" class="grey-text text-lighten-3" href="#!">关于</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="footer-copyright">
            <div class="container">
                © 2017 Touko @Sora
                <a class="grey-text text-lighten-4 right" href="http://sora.studio/">Sora Studio</a>
            </div>
        </div>
    </footer>
</section>

<!-- Modal Structure -->
<div id="notifications" class="modal modal-fixed-footer">
    <div class="modal-content">
        <h4>弘毅活动室预约注意事项</h4>
        <h2><a id="_0"></a>活动室使用规则</h2>
        <ol>
            <li>
                <p>活动室预约总体遵循先来后到的原则（即先预约者优先使用），如学堂内有重要会议（有辅导员、院领导参与的会议等）需在活动室召开，则参会者对同时段的活动室具有优先使用权。</p>
            </li>
            <li>
                <p>到达活动室的时间不得晚于预约时间15分钟。</p>
            </li>
            <li>
                <p>每次使用完活动室后15分钟内须将钥匙归还至当天值班人员处。</p>
            </li>
            <li>
                <p>如果需要中途离开，则须锁好门窗，自己保管好钥匙后离开，并在预约时间结束后归还钥匙。</p>
            </li>
            <li>
                <p>活动室使用者须保持活动室环境干净整洁。到达活动室和离开活动室时须用手机拍照，并将照片发送至<strong>社团中心官方QQ（1451909411）</strong>。照片要具有时间信息（时间水印或墙上挂钟），如果当天有值班人员现场检查，则在离开时可以不用拍照。
                </p>
            </li>
            <li>
                <p>活动室使用者需保证活动室公共设施的完好。</p>
            </li>
        </ol>
        <h2><a id="_13"></a>预约者信用制度</h2>
        <ol>
            <li>
                <p>以下规则仅针对活动室<strong>预约者</strong>，预约者对其预约时段内的活动室使用负责。</p>
            </li>
            <li>
                <p>活动室采用信用分级制度，共分为A、B、C、D、E、F六个等级。初始等级为A级，违反使用规则会有相应的降级措施。降到E级将失去活动室使用权一学期，降到F级将失去活动室使用权一年。</p>
            </li>
            <li>
                <ol>
                    <li>
                        <p>若使用者违反<strong>活动室使用规则第5条</strong>，预约者的信用等级降一级，并在下一次活动室被使用前将活动室打扫干净。</p>
                    </li>
                    <li>
                        <p>若使用者违反<strong>活动室使用规则第6条</strong>，且不主动上报的，预约者的信用等级降两级，并照价赔偿损失；若损坏公共设施但主动上报的，仅需照价赔偿损失。</p>
                    </li>
                    <li>
                        <p>若使用者违反<strong>活动室使用规则第2/3/4条</strong>，预约者信用等级降一级。</p>
                    </li>
                </ol>
            </li>
            <li>
                <p>其他违反规则的行为将视情节轻重给予惩罚措施。</p>
            </li>
        </ol>
        <pre><code>
注：
1. 活动室使用者包括预约者，预约者对该次预约负全部责任；
2. 本规则自10月10日起试用，试用期为一个月，一个月后将就试用中出现的问题对本规则进行修订；
3. 本规则最终解释权归弘毅学堂社团中心所有。
</code></pre>

    </div>
    <div class="modal-footer">
        <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat">Agree</a>
    </div>
</div>

<!--Import jQuery before materialize.js-->
<script type="text/javascript" src="{{ url_for('static', filename='jquery/js/jquery-3.2.1.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='materializecss/js/materialize.min.js') }}"></script>
<!-- Custom js files -->
<script type="text/javascript" src="{{ url_for('static', filename='custom/js/main.js') }}"></script>
<!-- string-format.js -->
<script type="text/javascript" src="{{ url_for('static', filename='custom/js/string-format.js') }}"></script>

{% block js_files %}{% endblock js_files %}
</body>

</html>